---
permalink: online-help/concept-managing-reports.html
sidebar: sidebar
keywords: 
summary: 'Active IQ Unified Manager enables you to create and manage reports directly from the Unified Manager user interface so that you can view information about the health, capacity, performance, and protection relationships of storage objects in your clusters. Reviewing this information can help you to identify potential problems before they occur.'
---
= Managing reports
:icons: font
:imagesdir: ../media/

[.lead]
Active IQ Unified Manager enables you to create and manage reports directly from the Unified Manager user interface so that you can view information about the health, capacity, performance, and protection relationships of storage objects in your clusters. Reviewing this information can help you to identify potential problems before they occur.

You can download reports as comma-separated values (.csv), Microsoft Excel (.xlsx), or PDF files. You can also schedule a report to be sent using email to a group of recipients. The reports are sent as email attachments.

In addition to generating reports from the user interface, you can extract health and performance data from Unified Manager using these additional methods:

* Using Open Database Connectivity (ODBC) and ODBC tools to directly access the database for cluster information
* Executing Unified Manager REST APIs to return the information you are interested in reviewing

*Related information*

xref:task-exporting-storage-data-as-reports.adoc[Exporting storage data as reports]

xref:concept-unified-manager-databases-accessible-for-reporting.adoc[Unified Manager databases accessible for custom reporting]

xref:concept-using-unified-manager-rest-apis-ocum.adoc[Using Unified Manager REST APIs]
