---
permalink: online-help/concept_backup_and_restore_using_netapp_snapshots.html
sidebar: sidebar
keywords: 
summary: 'A NetApp Snapshot backup creates a point-in-time image of the Unified Manager database and configuration files that you can use to restore in case of a system failure or data loss. You schedule a Snapshot backup to be written to a volume on one of your ONTAP clusters periodically so that you always have a current copy.'
---
= Backup and restore using NetApp Snapshots
:icons: font
:imagesdir: ../media/

[.lead]
A NetApp Snapshot backup creates a point-in-time image of the Unified Manager database and configuration files that you can use to restore in case of a system failure or data loss. You schedule a Snapshot backup to be written to a volume on one of your ONTAP clusters periodically so that you always have a current copy.

[NOTE]
====
This functionality is available only when Unified Manager is installed on a Red Hat Enterprise Linux or CentOS Linux server.
====

Snapshot backups take very little time, usually just a few minutes, and the Unified Manager database is locked for a very short timeframe, so there is very little disruption to your installation. The image consumes minimal storage space and incurs negligible performance overhead because it records only changes to files since the last Snapshot copy was made. Because the Snapshot is created on an ONTAP cluster, you can take advantage of other NetApp features such as SnapMirror to create secondary protection, if needed.

Before beginning a backup operation, Unified Manager performs an integrity check to verify that the destination system is available.

Note that you can restore a Snapshot backup only on the same version of Unified Manager. For example, if you created a backup on Unified Manager 9.8, the backup can be restored only on Unified Manager 9.8 systems.
