---
permalink: online-help/reference-setup-autosupport-page.html
sidebar: sidebar
keywords: 
summary: 'The AutoSupport page enables you to enable periodic AutoSupport, or to send an on-demand AutoSupport message to NetAppActive IQ. AutoSupport is enabled by default.'
---
= AutoSupport page
:icons: font
:imagesdir: ../media/

[.lead]
The AutoSupport page enables you to enable periodic AutoSupport, or to send an on-demand AutoSupport message to NetAppActive IQ. AutoSupport is enabled by default.

== Information area

* *System ID*
+
Displays the system ID for this Unified Manager server.

== On-Demand AutoSupport area

You can generate and send an on-demand message to technical support, a specified email recipient, or both:

* *Send to Technical Support*
+
Indicates that you want to send an on-demand message to technical support for any issues that have occurred.

* *Send to Email Recipient*
+
Indicates that you want to send an on-demand message to a specified recipient for any issues that have occurred.

* *Generate and Send AutoSupport*
+
Generates and sends an on-demand message to technical support, a specified email recipient, or both for any issues that have occurred.

== Periodic AutoSupport area

Enables you to have specific, predefined messages to technical support for issue diagnosis and resolution periodically generated.

* *Enable Sending AutoSupport Data Periodically to Active IQ*
+
Indicates that you want to enable the periodic AutoSupport functionality. This functionality is enabled by default.

== HTTP Proxy area

You can designate a proxy to provide Internet access in order to send AutoSupport content to support if your environment does not provide direct access from the Unified Manager server.

* *Use HTTP proxy*
+
Check this box to identify the server being used as the HTTP proxy.
+
Enter the host name or IP address of the proxy server, and the port number used to connect to the server.

* *Use authentication*
+
Check this box if you need to provide authentication information to access the server being used as the HTTP proxy.
+
Enter the user name and the password required to authenticate with the HTTP proxy.

[NOTE]
====
HTTP proxies that provide only Basic Authentication are not supported.
====

*Related information*

xref:task-enabling-periodic-autosupport.adoc[Enabling periodic AutoSupport]

xref:task-sending-an-on-demand-autosupport-message.adoc[Sending on-demand AutoSupport messages]
