---
permalink: online-help/reference-snapmirror-and-vault-relationship-events.html
sidebar: sidebar
keywords: 
summary: 'SnapMirror and Vault relationship events provide you with information about the status of your Asynchronous SnapMirror and Vault relationships so that you can monitor for potential problems. Events are grouped by impact area and include the event and trap name, impact level, source type, and severity.'
---
= SnapMirror and Vault relationship events
:icons: font
:imagesdir: ../media/

[.lead]
SnapMirror and Vault relationship events provide you with information about the status of your Asynchronous SnapMirror and Vault relationships so that you can monitor for potential problems. Events are grouped by impact area and include the event and trap name, impact level, source type, and severity.

== Impact area: protection
[options="header"]
|===
| Event name(Trap name)| Impact level| Source type| Severity
a|
Asynchronous Mirror and Vault Unhealthy(ocumEvtMirrorVaultRelationshipUnhealthy)

a|
Risk
a|
SnapMirror relationship
a|
Warning
a|
Asynchronous Mirror and Vault Broken-off(ocumEvtMirrorVaultRelationshipStateBrokenoff)

a|
Risk
a|
SnapMirror relationship
a|
Error
a|
Asynchronous Mirror and Vault Initialize Failed(ocumEvtMirrorVaultRelationshipInitializeFailed)

a|
Risk
a|
SnapMirror relationship
a|
Error
a|
Asynchronous Mirror and Vault Update Failed(ocumEvtMirrorVaultRelationshipUpdateFailed)

a|
Risk
a|
SnapMirror relationship
a|
Error
a|
Asynchronous Mirror and Vault Lag Error(ocumEvtMirrorVaultRelationshipLagError)

a|
Risk
a|
SnapMirror relationship
a|
Error
a|
Asynchronous Mirror and Vault Lag Warning(ocumEvtMirrorVaultRelationshipLagWarning)

a|
Risk
a|
SnapMirror relationship
a|
Warning
a|
Asynchronous Mirror and Vault Resync Failed(ocumEvtMirrorVaultRelationshipResyncFailed)

a|
Risk
a|
SnapMirror relationship
a|
Error
|===
