---
settings:
  name: Active IQ Unified Manager 9.8
  internal:
    pdf_enabled: true
    lipi_enabled: false
  prod:
    pdf_enabled: true
  versions:
    - name: Unified Manager
      url: /active-iq-unified-manager-98
      version-number: "9.8"
    - name: Unified Manager
      url: /active-iq-unified-manager-99
      version-number: "9.9"
    - name: Unified Manager
      url: /active-iq-unified-manager-97
      version-number: "9.7"
    - name: Unified Manager
      url: /oncommand-unified-manager-95
      version-number: "9.5"
sidebar:
  entries:
    - title: Home
      url: "/index.html"
    - title: Release notes
      url: "/release-notes.html"
    - title: Get started
      entries:
        - title: Quick start install for VMware vSphere
          url: /install-vapp/qsg-vapp.html
        - title: Quick start install for Linux
          url: /install-linux/qsg-linux.html
        - title: Quick start install for Windows
          url: /install-windows/qsg-windows.html  
    - section: install-vapp
    - section: install-linux
    - section: install-windows
    - section: config
    - section: online-help
    - section: performance-checker
    - section: health-checker
    - section: data-protection
    - section: reporting
    - section: api-automation
    - title: Legal notices
      url: "/legal-notices.html"
homepage:
  tiles:
    - title: Get started
      links:
        - title: Release notes
          url: /release-notes.html
        - title: Quick start install for VMware vSphere
          url: /install-vapp/qsg-vapp.html
        - title: Quick start install for Linux
          url: /install-linux/qsg-linux.html
        - title: Quick start install for Windows
          url: /install-windows/qsg-windows.html  
    - title: More resources
      links:
        - title: Unified Manager videos
          url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7mp3jFSg0IJgo3oeDQRY-Gl
        - title: Unified Manager blogs 
          url: https://www.netapp.com/blog/#q=active%20iq%20unified%20manager&t=Blogs&sort=%40publish_date_mktg%20descending&layout=card&f:@facet_language_mktg=[English] 
        - title: Documentation for the latest version of Active IQ Unified Manager
          url: https://docs.netapp.com/us-en/active-iq-unified-manager/index.html
